// import Head from "next/head";
// import NavBar from "../NavBar";

// export default function home(){
//     return(
//         <div>
//             <Head> 
//                 <title>Menu </title>
//                 <meta name="description" content="Generated by create next app"/>
//                 <link rel="icon" href="/pro.ico"/>
//             </Head>
//             <NavBar/>
//         </div>
        
//     );
// }